# Generated by Django 4.2.4 on 2025-06-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
